### ISSUE TITLE
Invalid date format when use mysql 8

### ISSUE THREAD

**Issue by gonzaloebiz** [mailchimp/mc-magento2#1066]
the cron finish with an invalid date format when use MySQL 8
This issue is valid only for magento 2.4, if you are experimenting this issue and have a version of magento < 2.4, take a look at https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#database only 2.4 support MySQL 8

**Comment by wigman** [comment]
Leaving this comment as a reference for people encountering the same SQL error, which this change solved:

```sql
SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '', query was: SELECT `main_table`.*, `m4m`.* FROM `newsletter_subscriber` AS `main_table` LEFT JOIN `xxxxx`.`mailchimp_sync_ecommerce` AS `m4m` ON m4m.related_id = main_table.subscriber_id and m4m.type = 'SUB' and m4m.mailchimp_store_id = 'xxxxx' WHERE (`subscriber_status` = 1) AND (`main_table`.`store_id` = 1) AND (m4m.mailchimp_sync_delta IS null OR (m4m.mailchimp_sync_delta > '' and m4m.mailchimp_sync_modified = 1)) LIMIT 100
```

**Comment by aaronhuang1** [comment]
updated to version-102.3.42 https://prnt.sc/yz7xdo , still same issues https://prnt.sc/yz7uyq

**Comment by gonzaloebiz** [comment]
hi @aaronhuang1 

this query is generated here, https://github.com/mailchimp/mc-magento2/blob/develop-2.3/Model/Api/Subscriber.php#L61-L73 specifically the datetime value is taken here https://github.com/mailchimp/mc-magento2/blob/develop-2.3/Model/Api/Subscriber.php#L72
If you look at here https://github.com/mailchimp/mc-magento2/blob/develop-2.3/Helper/Data.php#L662-L669 getMCMinSyncDateFlag the function never returns ''

So please, double-check that the function getMCMinSyncDateFlag is the same

Best

**Comment by aaronhuang1** [comment]
Hi

I have compared the file is the same, the cronjob sync failed
https://prnt.sc/z38ik4 due to the query error, I ran the query directly
from DB and also got a datetime error, hope you have a solution to fix this.

let me know if you need any additional information


Regards,


*Aaron Huang *General Manager | Mobileciti


_______________________________________________________
W: www.mobileciti.com.au | E: aaron@mobileciti.com.au
P: 02 9893 8886 / 8599 1682 (Direct) | F: 02 9893 8006

Shop 7B, 118 Church Street, Parramatta NSW 2150
Click Here! <http://www.mobileciti.com.au/> Order Online Today!

*P* *Please consider the environment before printing this e-mail*

**Comment by gonzaloebiz** [comment]
hi @aaronhuang1 

i just try with some logs. modifying this part https://github.com/mailchimp/mc-magento2/blob/develop-2.3/Model/Api/Subscriber.php#L60-L74 with

```
        $this->_helper->log(__METHOD__);
        $collection = $this->_subscriberCollection->create();
        $collection->addFieldToFilter('subscriber_status', ['eq' => 1])
            ->addFieldToFilter('store_id', ['eq' => $storeId]);
        $collection->getSelect()->joinLeft(
            ['m4m' => $this->_helper->getTableName('mailchimp_sync_ecommerce')],
            "m4m.related_id = main_table.subscriber_id and m4m.type = '".
            \Ebizmarts\MailChimp\Helper\Data::IS_SUBSCRIBER.
            "' and m4m.mailchimp_store_id = '".$listId."'",
            ['m4m.*']
        );
        $collection->getSelect()->where("m4m.mailchimp_sync_delta IS null ".
            "OR (m4m.mailchimp_sync_delta > '".$this->_helper->getMCMinSyncDateFlag().
            "' and m4m.mailchimp_sync_modified = 1)");
        $collection->getSelect()->limit(self::BATCH_LIMIT);
        $this->_helper->log((string)$collection->getSelect());

```

and the function https://github.com/mailchimp/mc-magento2/blob/develop-2.3/Helper/Data.php#L662-L669 with this

```
    public function getMCMinSyncDateFlag($storeId = null)
    {
        $syncDate = $this->getConfigValue(self::XML_PATH_SYNC_DATE, $storeId);
        $this->log("syncdate [$syncDate]");
        if ($syncDate=='') {
            $syncDate = '0000-00-00';
        }
        $this->log("syncdate [$syncDate]");
        return $syncDate;
    }
```

and this is the result

```
[2021-02-11 15:40:04] MailChimpLogger.INFO: Ebizmarts\MailChimp\Model\Api\Subscriber::sendSubscribers
 [] []
[2021-02-11 15:40:04] MailChimpLogger.INFO: syncdate []
 [] []
[2021-02-11 15:40:04] MailChimpLogger.INFO: syncdate [0000-00-00]
 [] []
[2021-02-11 15:40:04] MailChimpLogger.INFO: SELECT `main_table`.*, `m4m`.* FROM `newsletter_subscriber` AS `main_table`
 LEFT JOIN `mc-magento23`.`mailchimp_sync_ecommerce` AS `m4m` ON m4m.related_id = main_table.subscriber_id and m4m.type = 'SUB' and m4m.mailchimp_store_id = '431926bb0b' WHERE (`subscriber_status` = 1) AND (`main_table`.`store_id` = 1) AND (m4m.mailchimp_sync_delta IS null OR (m4m.mailchimp_sync_delta > '0000-00-00' and m4m.mailchimp_sync_modified = 1)) LIMIT 100
 [] []
```

Best

**Comment by aaronhuang1** [comment]
Hi Great

looks like the update query is working now, can you apply change to the
patch file

other question we got very large mailchimp_errors table, can i just empty
the table


[image: image.png]




******************

SELECT `main_table`.*, `m4m`.* FROM `newsletter_subscriber` AS `main_table`
 LEFT JOIN `mc-magento23`.`mailchimp_sync_ecommerce` AS `m4m` ON
m4m.related_id = main_table.subscriber_id and m4m.type = 'SUB' and
m4m.mailchimp_store_id = '431926bb0b' WHERE (`subscriber_status` = 1)
AND (`main_table`.`store_id` = 1) AND (m4m.mailchimp_sync_delta IS
null OR (m4m.mailchimp_sync_delta > '0000-00-00' and
m4m.mailchimp_sync_modified = 1)) LIMIT 100


[image: image.png]

Regards,


*Aaron Huang *General Manager | Mobileciti


_______________________________________________________
W: www.mobileciti.com.au | E: aaron@mobileciti.com.au
P: 02 9893 8886 / 8599 1682 (Direct) | F: 02 9893 8006

Shop 7B, 118 Church Street, Parramatta NSW 2150
Click Here! <http://www.mobileciti.com.au/> Order Online Today!

*P* *Please consider the environment before printing this e-mail*

**Comment by gonzaloebiz** [comment]
No need to apply, the fix is already applied in the 10*.*.42
Yes, you can truncate the table

**Comment by aaronhuang1** [comment]
Hi

thanks, indexing looks like working now, will let you know if I see any
issues, I will also update the comments

with error log build up quite quickly, already 83k log since 12-Feb

would be good to see below improvement

- Mailchimp errors (admin end not option to clear log)
https://prnt.sc/zj55m7
- Ecommerce configuration "Rest errors" not working https://prnt.sc/zj5fu3


Regards,


*Aaron Huang *General Manager | Mobileciti


_______________________________________________________
W: www.mobileciti.com.au | E: aaron@mobileciti.com.au
P: 02 9893 8886 / 8599 1682 (Direct) | F: 02 9893 8006

Shop 7B, 118 Church Street, Parramatta NSW 2150
Click Here! <http://www.mobileciti.com.au/> Order Online Today!

*P* *Please consider the environment before printing this e-mail*
