### ISSUE TITLE
Magento 2.2 compatibility

### ISSUE THREAD

**Issue by torlokken** [mailchimp/mc-magento2#116]
Please add 2.2 compatibility

**Comment by gonzaloebiz** [comment]
Hi @torlokken 

we just test it in magento 2.2.1 and all works OK.
Are you already trying?

Best

**Comment by lstellway** [comment]
Hi @gonzaloebiz,

I see an update `1.1.32` which I believe includes a fix for an issue I'm experiencing. The update specifies a dependency for `magento/framework: 100.1.*` - is this intentional? The previous version was dependent on `101.0.*`. 

I am on Magento `2.2.6`, which utilizes `magento/framework:101.0.6`, and cannot update the module.

**Comment by gonzaloebiz** [comment]
Look at https://github.com/mailchimp/mc-magento2/releases, you must specify which version you want to install

Best
