### ISSUE TITLE
Module continually attempts to sync records in mailchimp_sync_ecommerce that won't sync and never gives up

### ISSUE THREAD

**Issue by mpchadwick** [mailchimp/mc-magento2#1346]
## Issue Description

What we're seeing is that certain records in `mailchimp_sync_ecommerce` fail to sync for one reason or another (for example a customer record with an email address that fails Mailchimp validation), but the module will indefinitely attempt to sync that record.

Each time it will fail and a record will get created in `mailchimp_errors`. Eventually the data in `mailchimp_errors` will get so large that the `ebizmarts_clean_batches` cron will become unbearably slow. The module should give up on syncing records after they've failed more than a certain amount of times (for example if it failed to sync 5 times, mark it as permanently failed). Other modules elegantly handle this situation and it should be handled within the Mailchimp connector as well.

### Preconditions

Have a record in `mailchimp_sync_ecommerce` that the Mailchimp API won't accept, for example a customer record with an `@example.com` email address will fail to sync

### Steps to reproduce

Repeatedly run the `ebizmarts_ecommerce` cron.

### Actual and Expected result

Expected: 

At a certain point the module realizes the data won't sync and stops trying to sync it.

Actual:

The module continually tries to sync and never gives up.

**Comment by gonzaloebiz** [comment]
Please follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

**Comment by hnsr** [comment]
Running into the same issue, even after the fix for cleaning `mailchimp_errors`. This table is filling up exponentially faster because batches are getting stuck on the 'pending' state even if they've already been completed, en keep producing rows in `mailchimp_errors` on every cron run.

In our case this seems to be happening due to batch item responses having an `operation_id` of `null`. The `explode()` in `\Ebizmarts\MailChimp\Model\Api\Result::processEachResponseFile` trips over this triggering an undefined array access, which prevents the batch status from being set to either error or complete.

We have a pretty busy shop and this table ended up growing up to 150GB in size, filling up the file system

**Comment by hnsr** [comment]
@gonzaloebiz would it be preferable if I opened a new issue for this? I can't quite figure out the exact pre-conditions or steps-to-reproduce that trigger this bug for us (aside from the technical detail about `operation_id` being null described above), so I am not sure if I can follow the issue reporting guidelines to the letter
