### ISSUE TITLE
ebizmarts_ecommerce job unchecks "Use Default Value" checkbox for some product attributes

### ISSUE THREAD

**Issue by PachisPachis** [mailchimp/mc-magento2#1758]
### Preconditions
Magento 2.4.6-p1
mc-magento2 v103.4.53
One store view with Id=1

### Steps to reproduce
Create new simple product with basic data
Select "Default Store View" scope, you will notice that all "Use Default Value" checkboxes are checked. This is the desired and factory behaviour for Magento.
Run ebizmarts_ecommerce cron job

### Actual result
After running the cron job, you will notice that the checkbox "Use Default Value" is now unchecked for some attributes like Product Name, Tax Class, Visibility, etc... 
This is totally unexpected and generates a problem because from this moment you will have two values for the same attribute, one for the global scope, another one for the store view with id=1. If you usually update products in global scope (programmatiacally like us), you won't notice that there are subyacent values in store view scope.

### Expected result
The module shouldn't modify my product data in any way, even less without warning the user.

**Comment by DarthFly** [comment]
The culprit here seems to be this commit - https://github.com/mailchimp/mc-magento2/commit/e3a1089095ebcd0e9c61c9a9bb91598dbb1701c1
The code 
```
    $product = $this->productFactory->create()->load($entityId);
...
    $product->save();
```
saves product on the currently assumed scope (main cron file sets it), updates attributes, runs a lot of unnecessary things to just trigger some Before/After observers that seem like do nothing in this case.
Just comment the whole part of from creating product and saving it, I don't see any benefits from it.
