### ISSUE TITLE
Merge Names not synching

### ISSUE THREAD

**Issue by msawyers** [mailchimp/mc-magento2#188]
Issue Description
Customer Groups, Gender and Customer Birthdays not synching to mailchimp from magento

Steps to reproduce
install mc-magento 1.0.26
synch data

Expected Result:
All relevant data should synch with Magento 

Actual Result
![magento2](https://user-images.githubusercontent.com/8907629/35462853-d680b4a6-02bb-11e8-83cf-c258fe014558.PNG)

![magento1](https://user-images.githubusercontent.com/8907629/35462865-e6583156-02bb-11e8-803a-8e82fb02376b.PNG)

![mailchimp](https://user-images.githubusercontent.com/8907629/35462869-eb974b3e-02bb-11e8-9982-84ebb6f9b22b.PNG)

**Comment by gonzaloebiz** [comment]
Hi @msawyers 

thanks for your feedback.
Check if ALL the mapped fields are created in MailChimp.
Also, check in the MailChimp error grid what is the error.

Best

**Comment by jhruehl** [comment]
The actual problem with the syncing of the merge field is (at least in Magento 2.2.2) in the production mode, which handles fatal errors differently.

If merge fields are used, the Mailchimp extension actually creates a collection of ALL customer attributes and makes a ->getSource() call on every single entry in the collection to then get the options entries for each attribute (to get the labels for the options and not only sync the option ID). But if the attribute doesn't have a source class referenced, because it's just static like the attribute `is_confirmed`, this `getSource` call leads to a fatal error in production mode.

So there are two major issues involved:
1. The attribute collection is created for every single subscriber entry, which is going to be synced. This is quite a huge waste of resources and actually slows the cron process down a lot (I prevented that by adding a plugin to add the wanted merge data myself and the ecommerce cron immediatly got a lot faster).
2. It simply doesn't work as long as there are customer attributes given without a referenced source class. And because it is a fatal error, it cannot be caught as an exception.

**Comment by gonzaloebiz** [comment]
Hi @jhruehl 

thanks for your feedback.
In order to your point.

> The attribute collection is created for every single subscriber entry, which is going to be synced. This is quite a huge waste of resources and actually slows the cron process down a lot (I prevented that by adding a plugin to add the wanted merge data myself and the ecommerce cron immediatly got a lot faster).

You can view at this https://github.com/mailchimp/mc-magento2/blob/develop/Helper/Data.php#L299 that the data is loaded only once.
I know, would be better if we detect that already loaded at https://github.com/mailchimp/mc-magento2/blob/develop/Helper/Data.php#L324 so i take note of this.

I will take a look to `is_confirmed` field

Best

**Comment by jhruehl** [comment]
Sorry. Just saw that it's only loaded once and then saved in a protected variable of the object, but the problem with the `getSource()` calls on attributes, which don't have a source class reference in the `eav_attribute` table, is a problem. I debugged the code to that point and then google gave me some inacceptable solutions like 'adding the reference myself to the attribute'.

But I just needed the first name, last name and the magento id, so a simple around plugin sufficed:
`public function aroundGetMergeVars(\Ebizmarts\MailChimp\Helper\Data $subject, callable $proceed, \Magento\Customer\Model\Customer $customer, $storeId)
    {

        $result = [];

        $result['MAGENTO_ID'] = $customer->getId();

        if ($firstname = $customer->getData('firstname'))
        {
            $result['FNAME'] = $firstname;
        }

        if ($lastname =  $customer->getData('lastname'))
        {
            $result['LNAME'] = $lastname;
        }

        return $result;
    }`

**Comment by jhruehl** [comment]
Furthmore you'll only get the error, if you run Magento 2 in production mode. It doesn't occur in the developer mode. At least not in my local environment.

**Comment by gonzaloebiz** [comment]
@msawyers @jhruehl 

please, apply the associated commit.

Best
