### ISSUE TITLE
web_hooks error somewhere - first/last name being required

### ISSUE THREAD

**Issue by dan-ding** [mailchimp/mc-magento2#302]
magento 2.1.x
magento 2.2.x

not really clear where where this is firing from except it occurs during cron.
vendor/mailchimp/mc-magento2/Model/Api/Customer.php ?

in cron schedule table:
job_code: ebizmarts_webhooks
messages:
"First Name" is a required value.
 "First Name" length must be equal or greater than 1 characters.
 "Last Name" is a required value.
 "Last Name" length must be equal or greater than 1 characters.

in log:
report.CRITICAL: "First Name" is a required value.
"First Name" length must be equal or greater than 1 characters.
"Last Name" is a required value.
"Last Name" length must be equal or greater than 1 characters. {"exception":"[object] (Magento\\Framework\\Validator\\Exception(code: 0): \"First Name\" is a required value.
\"First Name\" length must be equal or greater than 1 characters.
\"Last Name\" is a required value.
\"Last Name\" length must be equal or greater than 1 characters. at /vendor/magento/module-customer/Model/ResourceModel/Customer.php:170)"} []

**Comment by dan-ding** [comment]
possible dup of:
https://github.com/mailchimp/mc-magento2/issues/278

it's not clear to me.
a customer requires first/last name and that patch doesn't handle such a condition. maybe it's getting written over with a blank value?

**Comment by ebizmarts-keller** [comment]
Hello @dan-ding 

Because Magento requires for a customer to have a first and last name, is that we added the patch so that if this values are updated in Mailchimp to a null value, it doesn't attempt to update those fields on the customer in Magento (since that is what makes the cronjob fail).

If even after applying the patch you keep getting the error, perhaps something like what you have mentioned is happening, I don't know if Mailchimp allows you to save a blank space on the first name and last name, but if this was the case it is quite possibly that Magento will not accept that value and will break.

I will add some additional checks just in case to prevent that potential case, you'll see the commit soon.

**Comment by dan-ding** [comment]
ok @ebizmarts-keller , i'll take a looksee there. Thanks!

**Comment by NathanDayMF** [comment]
@ebizmarts-keller when can we expect 1.0.29 to be released?

**Comment by gonzaloebiz** [comment]
Hi @NathanDayMF 

we are in testing stage, i think 2/3 weeks

Best
