### ISSUE TITLE
Vulnerability issues in module

### ISSUE THREAD

**Issue by arendarenko** [mailchimp/mc-magento2#438]
I found that module has such vulnerability issues:

1. Unescaped values in templates (example: https://github.com/mailchimp/mc-magento2/blob/develop/view/frontend/templates/mailchimpjs.phtml#L4, 
2. Unescaped values in SQL-queries in Models/Helpers/Cron-files (example: https://github.com/mailchimp/mc-magento2/blob/develop/Model/Api/Cart.php#L139)

Those vulnerabilities may contain risks for websites security, so I think they should be fixed.

### Preconditions

    1. Magento CE 2.2.5
    2. mc-magento2 1.0.30.

**Comment by gonzaloebiz** [comment]
Hi @alexeya-ven 

thanks for your feedback.
You are right in the first point, we will review this changes.
In order to the second point, i think this is not necessary. In your example, the value of $mailchimpStoreId is returned by this line https://github.com/mailchimp/mc-magento2/blob/develop/Cron/Ecommerce.php#L118 and is an int value. 
Really i don't find a reason to escape this value or the mailchimpstoreid, or other values saved in the database, perhaps you can give me one.

Best

**Comment by arendarenko** [comment]
hi @gonzaloebiz 
module retrieves mailchimpStoreId from core_config_data which can be affected by another modules, so it can cause sql-injections. Maybe I've chose the wrong way to escape, and it should be done like this: https://github.com/mailchimp/mc-magento2/blob/develop/Model/ResourceModel/MailChimpInterestGroup.php#L32

**Comment by ihor-sviziev** [comment]
Hi @gonzaloebiz,
About 2nd point - any data retrieved both from customer or from DB - should be escaped **if possible**, here it's actually possible.

Vulnerabilities might be not really obvious, sometimes malware might be even in DB: [example](https://gwillem.gitlab.io/2017/02/14/triggered-malware/).

**Comment by ihor-sviziev** [comment]
@gonzaloebiz also in this module quite a lot of places where unserialize function is used.
Potentially [PHP Object Injection](https://www.owasp.org/index.php/PHP_Object_Injection) might be used.

It's better to convert everything to JSON format and use magento framework for serialization: https://github.com/magento/magento2/blob/2.2/lib/internal/Magento/Framework/Serialize/README.md
