### ISSUE TITLE
multi-site Customer Fields Mapping not syncing correctly

### ISSUE THREAD

**Issue by eddieturks** [mailchimp/mc-magento2#471]
'Customer Field Mapping' under Mailchimp>configuration uses Mailchimp field values are not set correctly per Website and Connected Store. Default Level Configuration is used.

### Preconditions

    1. Magento CE 2.2.4
    2. mc-magento2 1.0.32.
    3. Multiple Websites Configured
    4. Multiple Mailchimp Stores Connected to respective websites

### Steps to reproduce

In M2 admin Goto Mailchimp > Configuration

Configure More than 2 websites/connected stores at their website level. (To highlight the issue you can configure a connected website/store at the default level and check the customer field mapping at the website level). When no Default Config, exists for any fields under mailchimp > configuration. No Mailchimp field values will exist at the website level.

'Customer Field Mapping' under Mailchimp>configuration uses Mailchimp field values set at the 'Default' (primary) Configuration. 

### Actual and Expected result

Each connected website/store should sync with the mailchimp field values relevant to their selected/configured store.

**Comment by gonzaloebiz** [comment]
Hi @eddieturks 

thanks for your feedback.
Con you please share each store configuration? Your stores has the same domain?

Best

**Comment by eddieturks** [comment]
hi @gonzaloebiz 

Store config is as follows:

Default Config
--Website 1
----Website 1 view
------Website 1 store
--Website 2 
----Website 2 view
------Website 2 store
--Website 3 
----Website 3 view
------Website 3 store
--Website 4 
----Website 4 view
------Website 4 store

Each Website is on a separate domain so www.website1.com, www.website2.com, www.website3.com, and www.website4.com .

Let me know if that helps.

**Comment by Codmic** [comment]
We also have the same issue with version 1.0.32 on Magento Commerce 2.2.6. For now we downgraded to 1.0.30 so we can manually edit the Mailchimp fields in the configuration (since in older versions these are text inputs).

After downgrading you need to revert the version of the module in setup_module from 1.0.32 to 1.0.30 and also possible change the record(s) in the core_config table with path "mailchimp/general/map_fields". It possible contains an empty json encoded array ([]) and in the older module it's a serialized value (something like a:2:{i:5;s:5:"FNAME";i:7;s:5:"LNAME";} ) 

Hope this would be fixed, but for now 1.0.30 is working fine.

**Comment by andrewkett** [comment]
Is it possible to get an indication of when the 1.0.33 milestone might be released? This is quite a major issue for us right now and it would be good to at least have a ballpark, if it is going to be a while we'll need to roll out a patch in the mean time.

**Comment by gonzaloebiz** [comment]
Sorry but we don't have an ETA
