### ISSUE TITLE
Install MailChimp error in magento v2.3.0

### ISSUE THREAD

**Issue by tinh-ngo-niteco** [mailchimp/mc-magento2#573]
# Install MailChimp error in magento v2.3.0
Don't install mailchimp in magento v2.3.0
Environment: ubuntu 18.04, nginx, php7.2
## Issue Description
1, I clone code in github and copy to project
2, I run command line: ``` php bin/magento module:enable Ebizmarts_MailChimp ``` -> Response successfuly
```bash
The following modules have been enabled:
- Ebizmarts_MailChimp

To make sure that the enabled modules are properly registered, run 'setup:upgrade'.
Cache cleared successfully.
Generated classes cleared successfully. Please run the 'setup:di:compile' command to generate classes.
Info: Some modules might require static view files to be cleared. To do this, run 'module:enable' with the --clear-static-content option to clear them.
```
3, I run command line: ``` php bin/magento setup:upgrade ```

Show error:
```bash 
...
Module 'Magento_NewRelicReporting':
Module 'Ebizmarts_MailChimp':
Installing data... Class Mailchimp does not exist
```

### Preconditions

    1. Magento CE 2.3.0
    2. Ubuntu 18.04
    3. Nginx
    4. php7.2

Thank!

**Comment by gonzaloebiz** [comment]
Hi @tinh-ngo-niteco 

thanks for your feddback.
Please see at https://github.com/mailchimp/mc-magento2/blob/develop-2.3/composer.json#L28
As you can see, the extension depends on ebizmarts/mailchimp-lib
The best option is install the extension via composer:

composer require mailchimp/mc-magento2:dev-develop-2.3

until we have a released version for magento 2.3

Best

**Comment by jundat95** [comment]
thank, I try 👍

**Comment by tinh-ngo-niteco** [comment]
Thank, I try 👍

**Comment by tinh-ngo-niteco** [comment]
I try to install MailChimp with command line: composer require mailchimp/mc-magento2:dev-develop-2.3
I run command line: php bin/magento setup:upgrade -> response error
```bash
...
Module 'Ebizmarts_MailChimp':
Upgrading schema.. SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.mailchimp_sync_ecommerce' doesn't exist, query was: DESCRIBE `mailchimp_sync_ecommerce`

```
Check database, don't see table of mailchip
![screenshot from 2019-01-31 10-12-52](https://user-images.githubusercontent.com/38058535/52028233-de58b180-2540-11e9-92a1-cb8c6eacbaf1.png)

**Comment by adolforopeza** [comment]
hello is currently generating this message when I try to compile, 
bin/magento setup:di:compile 
magento 2.3.7-p2


-------------------------------------------------------------------------------------------------------------------------------------------------------------

Class Magento\Framework\View\Helper\SecureHtmlRenderer does not exist                                                                    
  Class Ebizmarts\MailChimp\Block\Mailchimpjs\Interceptor generation error: The requested class did not generate properly, because the 'g  
  enerated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' d  
  irectory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to   
  the signature of the related construct method, only.

**Comment by andrzejskowron** [comment]
> 

The same situation with our Magento 2.3.7-p2
