### ISSUE TITLE
Mailchimp doesn't sync deleted products to Mailchimp > Content > Products page

### ISSUE THREAD

**Issue by RedAtRareCandy** [mailchimp/mc-magento2#591]
## Title

Mailchimp doesn't sync deleted products to Mailchimp>Content>Products page

## Issue Description

Products can be updated but deleting Products leaves them in the Mailchimp.com's Content > Products section. 

### Preconditions

    1. Magento CE 2.3.0 without sample data installed.
    2. mc-magento2 dev-develop-2.3.

### Steps to reproduce

    1. Navigate to storefront's admin backend and log in.
    2. Go to Catalog > Products.
    3. Select a Virtual or Simple Product.
    4. Select Delete from the Actions dropdown field.
    5. Confirm the delete action.
    6. Log into Mailchimp.com
    7. Go to Content > Products.

### Actual and Expected result

Expected result:
    1. Mailchimp.com's Content > Products section should not show deleted Products.
    2. Magento Admin > MailChimp Configuration > Account Details section should count only Products that exist and are Enabled in Total Products count.

Actual result:
    1. Mailchimp.com's Content > Products section is showing deleted Products when it shouldn't.
    2. Magento Admin > MailChimp Configuration > Account Details section is counting deleted Products in Total Products count (which matches the value of Products in Mailchimp.com > Content > Products section).

### Additional information

Have changed the mailchimp_sync_deleted field to 1 on a Product for testing and it only removes the row from the mailchimp_sync_ecommerce table, not from Mailchimp's Content > Products page.

**Comment by gonzaloebiz** [comment]
Hi @RedAtRareCandy 

thanks for your feedback.
You are right, we never delete the products in mailchimp, but this is because if we delete the product when you see the order in mailchimp, the deleted product appear with no description and no image, so we must decide which is the better option, and we think the better option is no delete the product.
We also try putting the product as not visible in mailchimp, but this not affect the way that you see the product in mailchimp, so we are trying to find the best solution with mailchimp

Best
