### ISSUE TITLE
Loading screen stuck when attempting to save the API key.

### ISSUE THREAD

**Issue by brian-ebizmarts** [mailchimp/mc-magento2#940]
### Preconditions
    1. Magento 2
    2. mc-magento2 102.3.37, 101.2.37, 100.1.37
  
### Steps to reproduce
Set up the extension using a Mailchimp account with at least one mailchimp store created in Magento 1 but not having any one created in Magento 2.

**Comment by jproffer** [comment]
when will this be merged into master? I installed this extension from the marketplace, and it's still 102.3.37.

**Comment by SantiParagarino** [comment]
Hello @jproffer 
You can see the latest releases at https://github.com/mailchimp/mc-magento2/releases
Please note this issue only happens when there are no audiences in your Mailchimp account. You can easily get around it by creating an audience.
With new accounts, this problem does not happen because there is always a default list. You have to specifically delete it to experience this.

**Comment by jproffer** [comment]
this IS a new account.  Everything was setup brand new - magento2 setup,
plugin & mailchimp account.

**Comment by SantiParagarino** [comment]
@jproffer 
In that case you should already have an Audience, if you don't create one and this will not be a problem anymore.

Kind Regards.
